import { Priority, TaskStatus, Employee, Task, Project, UserRole, TaskDifficulty, KPI, OKR } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  { id: '1', name: 'Nguyễn Văn An', avatarUrl: 'https://picsum.photos/seed/1/100', role: UserRole.ADMIN, email: 'an.nguyen@company.com', phone: '0901234567', dob: '1985-05-15', password: '123456' },
  { id: '2', name: 'Trần Thị Bích', avatarUrl: 'https://picsum.photos/seed/2/100', role: UserRole.MEMBER, email: 'bich.tran@company.com', phone: '0912345678', dob: '1992-11-20', password: 'memberpassword1' },
  { id: '3', name: 'Lê Minh Cường', avatarUrl: 'https://picsum.photos/seed/3/100', role: UserRole.MEMBER, email: 'cuong.le@company.com', phone: '0987654321', dob: '1995-02-10', password: 'memberpassword2' },
];

const DEMO_KPIS: KPI[] = [
    { 
        id: 'kpi1', 
        employeeId: '1', 
        projectId: 'p1', 
        title: 'Hoàn thành 4 công việc', 
        target: 4, 
        timeframe: { period: 'month', date: '2025-08-01' } 
    },
    { 
        id: 'kpi2', 
        employeeId: '2', 
        projectId: 'p1', 
        title: 'Hoàn thành 5 công việc', 
        target: 5, 
        timeframe: { period: 'month', date: '2025-08-01' } 
    },
];

const DEMO_OKRS: OKR[] = [
    {
        id: 'okr1',
        employeeId: '2',
        projectId: 'p1',
        objective: 'Nâng cao chất lượng mã nguồn Frontend',
        keyResults: [
            { id: 'kr1-1', title: 'Tăng độ bao phủ test lên 80%', progress: 50 },
            { id: 'kr1-2', title: 'Tối ưu hóa thời gian tải trang xuống dưới 2s', progress: 75 },
        ],
        timeframe: { period: 'quarter', date: '2025-07-01' } // Q3 2025
    },
    {
        id: 'okr2',
        employeeId: '3',
        projectId: 'p1',
        objective: 'Cải thiện hiệu suất và độ ổn định của API',
        keyResults: [
            { id: 'kr2-1', title: 'Giảm thời gian phản hồi trung bình của API xuống 200ms', progress: 90 },
            { id: 'kr2-2', title: 'Đạt 99.9% uptime cho các dịch vụ chính', progress: 100 },
        ],
        timeframe: { period: 'quarter', date: '2025-07-01' } // Q3 2025
    }
];

export const INITIAL_PROJECTS: Project[] = [
  { 
    id: 'p1', 
    name: 'Dự án Alpha',
    contractUrl: 'https://docs.google.com/document/d/example',
    milestones: [
        { id: 'm1', name: 'Hoàn thành Giai đoạn Thiết kế', date: '2025-08-15', isCompleted: true },
        { id: 'm2', name: 'Ra mắt phiên bản Beta', date: '2025-09-01', isCompleted: false },
    ],
    attachments: [
        { id: 'a1', name: 'Bản đặc tả yêu cầu', url: 'https://docs.google.com/document/d/example2' },
        { id: 'a2', name: 'Kế hoạch dự án', url: 'https://docs.google.com/spreadsheets/d/example' },
    ],
    activityLog: [
      { id: 'ac1', authorId: '1', action: 'đã tạo công việc', timestamp: '2025-08-01T10:00:00Z', entity: { type: 'task', id: 't1', title: 'Thiết kế giao diện người dùng' } },
      { id: 'ac2', authorId: '2', action: 'đã thêm một bình luận', timestamp: '2025-08-13T14:30:00Z', entity: { type: 'comment', id: 'c1', title: 'vào công việc "Thiết kế giao diện người dùng"' } },
    ],
    kpis: DEMO_KPIS,
    okrs: DEMO_OKRS,
  },
  { 
    id: 'p2', 
    name: 'Chiến dịch Marketing Q3',
    contractUrl: '',
    milestones: [],
    attachments: [],
    activityLog: [],
    kpis: [],
    okrs: [],
  },
];

export const INITIAL_TASKS: Task[] = [
  // === Project Alpha (p1) Tasks ===
  {
    id: 't1',
    projectId: 'p1',
    sequenceId: 1,
    title: 'Thiết kế giao diện người dùng',
    description: 'Tạo wireframe và mockup cho trang chủ ứng dụng.',
    assigneeIds: ['1'],
    priority: Priority.HIGH,
    difficulty: TaskDifficulty.HARD,
    startDate: '2025-08-01',
    deadline: '2025-08-15',
    status: TaskStatus.IN_PROGRESS,
    notes: 'Sử dụng Figma để thiết kế. Tập trung vào trải nghiệm người dùng trên di động.',
    comments: [
      { id: 'c1', authorId: '2', text: 'Mockup ban đầu trông rất tốt!', timestamp: '2025-08-13T14:30:00Z' },
      { id: 'c2', authorId: '1', text: 'Đã cập nhật lại màu sắc theo yêu cầu.', timestamp: '2025-08-14T09:00:00Z' }
    ],
    tags: ['UI/UX', 'Figma', 'Mobile'],
    attachments: [
        { id: 'f1', name: 'Link Figma Mockups', url: 'https://figma.com/example' },
    ],
  },
  {
    id: 't2',
    projectId: 'p1',
    sequenceId: 2,
    title: 'Phát triển API',
    description: 'Xây dựng các endpoint API cho việc quản lý người dùng.',
    assigneeIds: ['2', '3'],
    priority: Priority.URGENT,
    difficulty: TaskDifficulty.HARD,
    startDate: '2025-08-05',
    deadline: '2025-08-10',
    status: TaskStatus.TODO,
    notes: 'Cần tích hợp xác thực JWT cho các endpoint quan trọng.',
    comments: [],
    tags: ['Backend', 'API', 'NodeJS'],
    attachments: [],
  },
  {
    id: 't4',
    projectId: 'p1',
    sequenceId: 3,
    title: 'Triển khai lên server Staging',
    description: 'Cấu hình và triển khai phiên bản mới nhất lên môi trường Staging.',
    assigneeIds: ['1', '2'],
    priority: Priority.HIGH,
    difficulty: TaskDifficulty.MEDIUM,
    startDate: '2025-08-28',
    deadline: '2025-08-30',
    status: TaskStatus.DONE,
    notes: 'Việc triển khai đã hoàn tất thành công lúc 4h chiều.',
    comments: [
        { id: 'c3', authorId: '1', text: 'Đã triển khai xong.', timestamp: '2025-08-30T16:00:00Z' }
    ],
    tags: ['DevOps', 'Staging'],
    attachments: [],
  },
  {
    id: 't5',
    projectId: 'p1',
    sequenceId: 4,
    title: 'Thiết kế Schema Database',
    description: 'Vẽ sơ đồ và định nghĩa các bảng cho cơ sở dữ liệu.',
    assigneeIds: ['3'],
    priority: Priority.HIGH,
    difficulty: TaskDifficulty.HARD,
    startDate: '2025-08-02',
    deadline: '2025-08-06',
    status: TaskStatus.IN_PROGRESS,
    notes: '',
    comments: [],
    tags: ['Backend', 'Database'],
    attachments: [],
  },
  {
    id: 't6',
    projectId: 'p1',
    sequenceId: 5,
    title: 'Xây dựng chức năng xác thực Frontend',
    description: 'Tạo form đăng nhập, đăng ký và quản lý session.',
    assigneeIds: ['2'],
    priority: Priority.MEDIUM,
    difficulty: TaskDifficulty.MEDIUM,
    startDate: '2025-08-16',
    deadline: '2025-08-22',
    status: TaskStatus.TODO,
    notes: 'Sử dụng React Context để quản lý trạng thái đăng nhập.',
    comments: [],
    tags: ['Frontend', 'React', 'Auth'],
    attachments: [],
  },
  {
    id: 't7',
    projectId: 'p1',
    sequenceId: 6,
    title: 'Module quản lý hồ sơ người dùng Backend',
    description: 'API cho phép xem, sửa, xóa hồ sơ người dùng.',
    assigneeIds: ['3'],
    priority: Priority.HIGH,
    difficulty: TaskDifficulty.MEDIUM,
    startDate: '2025-08-11',
    deadline: '2025-08-20',
    status: TaskStatus.TODO,
    notes: '',
    comments: [],
    tags: ['Backend', 'API'],
    attachments: [],
  },
  {
    id: 't8',
    projectId: 'p1',
    sequenceId: 7,
    title: 'Viết Unit Test cho API',
    description: 'Đảm bảo các endpoint API hoạt động đúng và ổn định.',
    assigneeIds: ['2', '3'],
    priority: Priority.MEDIUM,
    difficulty: TaskDifficulty.MEDIUM,
    startDate: '2025-08-18',
    deadline: '2025-08-24',
    status: TaskStatus.TODO,
    notes: 'Độ bao phủ test cần đạt trên 80%.',
    comments: [],
    tags: ['Backend', 'Testing'],
    attachments: [],
  },
  {
    id: 't9',
    projectId: 'p1',
    sequenceId: 8,
    title: 'Kiểm thử tích hợp',
    description: 'Kiểm tra sự phối hợp giữa frontend và backend.',
    assigneeIds: ['1'],
    priority: Priority.HIGH,
    difficulty: TaskDifficulty.EASY,
    startDate: '2025-08-25',
    deadline: '2025-08-28',
    status: TaskStatus.IN_PROGRESS,
    notes: '',
    comments: [],
    tags: ['QA', 'Testing'],
    attachments: [],
  },
  {
    id: 't10',
    projectId: 'p1',
    sequenceId: 9,
    title: 'Viết tài liệu hướng dẫn sử dụng',
    description: 'Tài liệu cho người dùng cuối về cách sử dụng các tính năng chính.',
    assigneeIds: ['2'],
    priority: Priority.LOW,
    difficulty: TaskDifficulty.EASY,
    startDate: '2025-09-01',
    deadline: '2025-09-07',
    status: TaskStatus.TODO,
    notes: '',
    comments: [],
    tags: ['Documentation'],
    attachments: [],
  },
  {
    id: 't11',
    projectId: 'p1',
    sequenceId: 10,
    title: 'Kiểm tra chất lượng và sửa lỗi cuối kỳ',
    description: 'Rà soát toàn bộ hệ thống, tìm và sửa các lỗi còn sót lại.',
    assigneeIds: ['1', '2', '3'],
    priority: Priority.URGENT,
    difficulty: TaskDifficulty.HARD,
    startDate: '2025-09-02',
    deadline: '2025-09-10',
    status: TaskStatus.DONE,
    notes: 'Tập trung vào các luồng nghiệp vụ quan trọng.',
    comments: [],
    tags: ['QA', 'Bugs'],
    attachments: [],
  },
  // === Marketing Campaign Q3 (p2) Tasks ===
  {
    id: 't3',
    projectId: 'p2',
    sequenceId: 1,
    title: 'Lên kế hoạch nội dung Social Media',
    description: 'Chuẩn bị bài đăng cho Facebook và Instagram trong tháng 8.',
    assigneeIds: ['2'],
    priority: Priority.MEDIUM,
    difficulty: TaskDifficulty.MEDIUM,
    startDate: '2025-08-10',
    deadline: '2025-08-20',
    status: TaskStatus.IN_PROGRESS,
    notes: '',
    comments: [],
    tags: ['Social Media', 'Content'],
    attachments: [],
  },
  {
    id: 't-demo-overdue',
    projectId: 'p2',
    sequenceId: 2,
    title: 'DEMO: Gửi Báo Cáo Phân Tích SEO',
    description: 'Đây là công việc demo để kiểm tra tính năng gửi email nhắc nhở cho công việc quá hạn.',
    assigneeIds: ['2'], // Trần Thị Bích
    priority: Priority.URGENT,
    difficulty: TaskDifficulty.EASY,
    startDate: '2025-07-01',
    deadline: '2025-07-05', // Clearly overdue if viewed in Aug 2025
    status: TaskStatus.IN_PROGRESS,
    notes: 'Email nhắc nhở sẽ được gửi đến bich.tran@company.com',
    comments: [],
    tags: ['Demo', 'SEO', 'Report'],
    attachments: [],
  },
  {
    id: 't12',
    projectId: 'p2',
    sequenceId: 3,
    title: 'Nghiên cứu thị trường & đối thủ cạnh tranh',
    description: 'Phân tích các chiến dịch marketing của đối thủ trong quý.',
    assigneeIds: ['2'],
    priority: Priority.HIGH,
    difficulty: TaskDifficulty.MEDIUM,
    startDate: '2025-08-01',
    deadline: '2025-08-08',
    status: TaskStatus.DONE,
    notes: 'Đã tổng hợp báo cáo và gửi cho quản lý.',
    comments: [],
    tags: ['Marketing', 'Research'],
    attachments: [],
  },
  {
    id: 't13',
    projectId: 'p2',
    sequenceId: 4,
    title: 'Xác định chỉ số đo lường hiệu quả (KPIs)',
    description: 'Thiết lập các KPI chính cho chiến dịch: reach, engagement, conversion rate.',
    assigneeIds: ['1'],
    priority: Priority.URGENT,
    difficulty: TaskDifficulty.MEDIUM,
    startDate: '2025-08-05',
    deadline: '2025-08-07',
    status: TaskStatus.DONE,
    notes: '',
    comments: [],
    tags: ['Marketing', 'KPIs'],
    attachments: [],
  },
  {
    id: 't14',
    projectId: 'p2',
    sequenceId: 5,
    title: 'Thiết kế ấn phẩm quảng cáo (Ảnh & Video)',
    description: 'Tạo các mẫu quảng cáo cho các nền tảng khác nhau.',
    assigneeIds: ['3'],
    priority: Priority.HIGH,
    difficulty: TaskDifficulty.HARD,
    startDate: '2025-08-15',
    deadline: '2025-08-25',
    status: TaskStatus.IN_PROGRESS,
    notes: '',
    comments: [],
    tags: ['Design', 'Ads'],
    attachments: [],
  },
  {
    id: 't15',
    projectId: 'p2',
    sequenceId: 6,
    title: 'Viết nội dung quảng cáo',
    description: 'Soạn thảo các thông điệp quảng cáo hấp dẫn.',
    assigneeIds: ['2'],
    priority: Priority.MEDIUM,
    difficulty: TaskDifficulty.EASY,
    startDate: '2025-08-20',
    deadline: '2025-08-26',
    status: TaskStatus.TODO,
    notes: 'Cần 3 phiên bản khác nhau để A/B testing.',
    comments: [],
    tags: ['Content', 'Copywriting'],
    attachments: [],
  },
  {
    id: 't16',
    projectId: 'p2',
    sequenceId: 7,
    title: 'Thiết lập chiến dịch Google Ads',
    description: 'Cài đặt các nhóm quảng cáo, từ khóa và ngân sách.',
    assigneeIds: ['2'],
    priority: Priority.HIGH,
    difficulty: TaskDifficulty.MEDIUM,
    startDate: '2025-08-27',
    deadline: '2025-08-31',
    status: TaskStatus.TODO,
    notes: '',
    comments: [],
    tags: ['Marketing', 'Google Ads'],
    attachments: [],
  },
  {
    id: 't17',
    projectId: 'p2',
    sequenceId: 8,
    title: 'Thiết lập chiến dịch Facebook Ads',
    description: 'Target đối tượng, chọn vị trí hiển thị và lên lịch quảng cáo.',
    assigneeIds: ['3'],
    priority: Priority.HIGH,
    difficulty: TaskDifficulty.MEDIUM,
    startDate: '2025-08-28',
    deadline: '2025-09-02',
    status: TaskStatus.TODO,
    notes: '',
    comments: [],
    tags: ['Marketing', 'Facebook Ads'],
    attachments: [],
  },
  {
    id: 't18',
    projectId: 'p2',
    sequenceId: 9,
    title: 'Triển khai chiến dịch Email Marketing',
    description: 'Gửi email thông báo chương trình khuyến mãi đến danh sách khách hàng.',
    assigneeIds: ['2'],
    priority: Priority.MEDIUM,
    difficulty: TaskDifficulty.EASY,
    startDate: '2025-09-01',
    deadline: '2025-09-05',
    status: TaskStatus.TODO,
    notes: '',
    comments: [],
    tags: ['Marketing', 'Email'],
    attachments: [],
  },
  {
    id: 't19',
    projectId: 'p2',
    sequenceId: 10,
    title: 'Theo dõi hiệu quả chiến dịch hàng tuần',
    description: 'Tổng hợp số liệu và đánh giá hiệu quả quảng cáo mỗi tuần.',
    assigneeIds: ['1', '2'],
    priority: Priority.MEDIUM,
    difficulty: TaskDifficulty.MEDIUM,
    startDate: '2025-09-01',
    deadline: '2025-09-30',
    status: TaskStatus.IN_PROGRESS,
    notes: 'Công việc lặp lại hàng tuần.',
    comments: [],
    tags: ['Marketing', 'Reporting'],
    attachments: [],
  },
  {
    id: 't20',
    projectId: 'p2',
    sequenceId: 11,
    title: 'A/B Testing các mẫu quảng cáo',
    description: 'Thử nghiệm các phiên bản quảng cáo khác nhau để tìm ra mẫu hiệu quả nhất.',
    assigneeIds: ['3'],
    priority: Priority.LOW,
    difficulty: TaskDifficulty.EASY,
    startDate: '2025-09-05',
    deadline: '2025-09-15',
    status: TaskStatus.TODO,
    notes: '',
    comments: [],
    tags: ['Marketing', 'A/B Test'],
    attachments: [],
  },
  {
    id: 't21',
    projectId: 'p2',
    sequenceId: 12,
    title: 'Chuẩn bị báo cáo giữa kỳ',
    description: 'Tổng kết kết quả của tháng đầu tiên và đề xuất cải tiến.',
    assigneeIds: ['1'],
    priority: Priority.HIGH,
    difficulty: TaskDifficulty.MEDIUM,
    startDate: '2025-09-15',
    deadline: '2025-09-17',
    status: TaskStatus.TODO,
    notes: '',
    comments: [],
    tags: ['Marketing', 'Reporting'],
    attachments: [],
  },
];

export const PRIORITY_STYLES: { [key in Priority]: { base: string; text: string } } = {
  [Priority.LOW]: { base: 'bg-green-500/10', text: 'text-green-400' },
  [Priority.MEDIUM]: { base: 'bg-yellow-500/10', text: 'text-yellow-400' },
  [Priority.HIGH]: { base: 'bg-orange-500/10', text: 'text-orange-400' },
  [Priority.URGENT]: { base: 'bg-red-500/10', text: 'text-red-400' },
};

export const DIFFICULTY_STYLES: { [key in TaskDifficulty]: { base: string; text: string } } = {
  [TaskDifficulty.EASY]: { base: 'bg-sky-500/10', text: 'text-sky-400' },
  [TaskDifficulty.MEDIUM]: { base: 'bg-amber-500/10', text: 'text-amber-400' },
  [TaskDifficulty.HARD]: { base: 'bg-fuchsia-500/10', text: 'text-fuchsia-400' },
};

export const STATUS_STYLES: { [key in TaskStatus]: { border: string; text: string; bg: string; } } = {
    [TaskStatus.TODO]: { border: 'border-blue-500', text: 'text-blue-300', bg: 'bg-blue-900/30' },
    [TaskStatus.IN_PROGRESS]: { border: 'border-yellow-500', text: 'text-yellow-300', bg: 'bg-yellow-900/30' },
    [TaskStatus.DONE]: { border: 'border-green-500', text: 'text-green-300', bg: 'bg-green-900/30' },
};